### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by Bezmundo** [douglasduteil/ui-slider-dirty#1]
When trying to implement this into ie8 it displays the following error:

``` html
  TypeError: Object doesn't support this property or method<div class="ui-slider__thumb ng-pristine ng-valid" data-ng-model="question.selectedValue" data-name="input" data-ng-required="" data-ng-mouseleave="show = false" data-ng-mouseenter="show = true">
```

The slider renders but you are not able to interact with it, is there anyway to get ie8 support without using the jquery alternative.

**Comment by douglasduteil** [comment]
wow sry no IE8 support for now...
(I'm planning on remaking this component BTW )
